#!/bin/bash
# vim: set filetype=sh:

ccat() {
    if command -v highlight >/dev/null 2>&1; then
        highlight -O ansi --force "$@"
    else
        cat "$@"
    fi
}

cless() {
    if command -v highlight >/dev/null 2>&1; then
        highlight -O ansi --force "$@" | \less -R
    else
        \less "$@"
    fi
}

alias cat='ccat'
alias less='cless'

# This script fails to load if sourced in a non-macOS
# platform
if [ -f ~/.macos_gvim_function ]; then
    source ~/.macos_gvim_function
fi
