#!/bin/bash
# vim: set filetype=sh:

ccat() {
    if command -v highlight >/dev/null 2>&1; then
        highlight -O ansi "$@"
    else
        cat "$@"
    fi
}

cless() {
    if command -v highlight >/dev/null 2>&1; then
        highlight -O ansi "$1" | less -R
    else
        less "$1"
    fi
}

alias cat='ccat'
alias less='cless'

if [ "$(uname -s)" == "Darwin" ]; then
    # Define a function instead of an alias
    gvim () {
        /Applications/MacVim.app/Contents/MacOS/Vim -g "$@"
    }
fi
