#!/bin/zsh
# ~/.zsh_functions

# Define a function instead of an alias
gvim () {
    /Applications/MacVim.app/Contents/MacOS/Vim -g "$@"
}

# Sverre's scripts

function rcd {
    cd "$(reldir $1)"
}

function scd {
    cd "$(searchdir $1)"
}

source ~/Projects/github/shell-utils/bash_my_functions

