#!/bin/zsh
# ~/.zsh_functions

# Define a function instead of an alias
gvim () {
    /Applications/MacVim.app/Contents/MacOS/Vim -g "$@"
}

# Sverre's scripts

function rcd {
    cd "$(reldir $1)"
}

function scd {
    cd "$(searchdir $1)"
}

function ccat() {
    if command -v highlight >/dev/null 2>&1; then
        highlight -O ansi --force "$@"
    else
        cat "$@"
    fi
}

function cless() {
    if command -v highlight >/dev/null 2>&1; then
        highlight -O ansi --force "$@" | \less -R
    else
        \less "$@"
    fi
}

alias cat='ccat'
alias less='cless'
