#!/bin/bash
# vim: set filetype=sh:

ccat() {
    if command -v highlight >/dev/null 2>&1; then
        highlight -O ansi --force "$@"
    else
        cat "$@"
    fi
}

cless() {
    if command -v highlight >/dev/null 2>&1; then
        highlight -O ansi --force "$@" | \less -R
    else
        \less "$@"
    fi
}

alias cat='ccat'
alias less='cless'

if [ "$(uname -s)" == "Darwin" ]; then
    gvim() {
        # Launch MacVim in the background
        /Applications/MacVim.app/Contents/MacOS/Vim -g "$@" &
    }
fi
