#!/bin/bash
# vim: set filetype=sh:

ccat() {
    if command -v highlight >/dev/null 2>&1; then
        highlight -O ansi --force "$@"
    else
        cat "$@"
    fi
}

cless() {
    if command -v highlight >/dev/null 2>&1; then
        highlight -O ansi --force "$@" | \less -R
    else
        \less "$@"
    fi
}

alias cat='ccat'
alias less='cless'

if [ "$(uname -s)" == "Darwin" ]; then
    script_dir=$(dirname "$(readlink -f "$BASH_SOURCE")")
    in_file=${script_dir}/macos/bash_env.sh
    if [ -f $in_file ]; then
        . $in_file
    fi
fi
